version: 0.0
os: linux

files:
  - source: ./service/service_main.py
    destination: /home/ec2-user/
  - source: ./cloudwatch-config.json
    destination: /home/ec2-user/

hooks:
  AfterInstall:
    - location: ./scripts/AfterInstall.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: ./scripts/ApplicationStart.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: ./scripts/ApplicationStop.sh
      timeout: 300
      runas: ec2-user

